### PR TITLE
Added the `flatten` convenience function...

### PR DESCRIPTION
**Pull request by kqr**
...to do case analysis on a `Result` value without explicit pattern matching

### CODE REVIEW

**Comment by rehno-lindeque** [comment]
This makes me think of `withDefault`. `flatten` seems terribly generic to me, I wonder we could name it something similar to that...

I'm almost tempted to have...
```elm
import Maybe
import Result

Maybe.withDefault x Nothing == x
Result.withDefault x (Err e) == x
```
...but this obviously doesn't do do the full case analysis.

I wanted to say perhaps something like `fromErr`...?
```elm
Maybe.withDefault x Nothing == x
Result.fromErr (always x) (Err e) == x
```
...but `from-` usually converts *to* a `Result` in Haskell conventions. On the other hand Elm might eschew this convention, I think I saw some discussion on the list at some point I think that said let's not use that convention? That might leave it free to be used for this kind of thing.

Or `withErr`...?
```elm
Maybe.withDefault x Nothing == x
Result.withErr (always x) (Err e) == x
```

Or `whenErr`...?
```elm
Maybe.withDefault x Nothing == x
Result.whenErr (always x) (Err e) == x
```
...again, assuming that Elm doesn't eventually use the `when` convention with monads the way that Haskell does.

I guess there's some connection to functions like `Bifunctor.first` / `Either.left` as well. so I could imagine this too...
```elm
Maybe.withDefault x Nothing == x
Result.fromFirst (always x) (Err e) == x
```

I feel like @evancz might have some good ideas around a naming convention?

**Comment by kqr** [comment]
@rehno-lindeque Yup, writing the code took two minutes, coming up with the name took well over fifteen minutes and I still agree with you that it's not a very good name – I just couldn't think of a better one within that time!

Other candidates I considered were `extract`, `toValue`, `toPlain`, `undecorate`, `unwrap`, `errIsOk` but none of them are really descriptive.

**Comment by srid** [comment]
How about:

```elm
Result.extract (always x) (Err e) == x
Result.extract (always x) (Ok y) == y
```

**Comment by rehno-lindeque** [comment]
I'm quite fond of `extract` too, perhaps we just go with that for now? It'll be up to the `core` maintainers to pick a better name when they decide to merge in. I'll happily publish with `extract` if you're in a hurry.

**Comment by kqr** [comment]
`flatten`, `join` and `concat` does sound like the same function, yes.

I'm fine with `extract`, I'm not one to linger too much at names. The main reason I submitted this PR was because @srid needed the function and I thought it fit this library well. :)

**Comment by rehno-lindeque** [comment]
Thanks! Published with `extract` as [1.1.0](http://package.elm-lang.org/packages/circuithub/elm-result-extra/1.1.0/Result-Extra).

**Comment by rehno-lindeque** [comment]
I noticed the `elim` function in http://package.elm-lang.org/packages/imeckler/either/1.0.0/Either#elim today. Thought I should mention it as another option, I kind of like it.

**Comment by rehno-lindeque** [comment]
e.g. perhaps
```elm
elim : (e -> x) -> (a -> x) -> Result e a -> x
elimErr : (e -> x) -> Result e x -> x
```

**Comment by srid** [comment]
+1. `elimErr` is explicit on what it does. `extract` ... not so much.

**Comment by kqr** [comment]
Yeah `elim` does a fuller case analysis. I don't personally see the need for that function, since it's basically `elimErr` followed by `map`, but `elimErr` might be a good name – I don't care particularly much for the name, as I've said. :)

**Comment by evancz** [comment]
I personally like `extract` and dislike abbreviating words in variable names. Saving a few chars is never worth it for me when the cost is new readers having a hard time.

In any case, I just wanted to mention `destruct` or `destructure` which matches with the idea of [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) and is pretty literal about what's happening here. Structure is being taken away.

**Comment by rehno-lindeque** [comment]
I was sort of wanting to go for `elim` but felt that it needs the same shape as it would have in `Either` just to be consistent with my typeclass-ish intuition of having the same name in two packages.

`extract` is just a bit weird to me in the above sense...

```elm
elim : (a -> r) -> (b -> r) -> Either a b -> r -- makes sense I think
elimLeft : (a -> b) -> Either a b -> b -- makes sense I think
elimRight : (b -> a) -> Either a b -> a -- makes sense I think

elimErr : (e -> a) -> Result e a -> a -- makes sense I think (isomorphic to elimLeft)

extract : (a -> r) -> (b -> r) -> Either a b -> r -- makes sense I think
extractLeft : (a -> b) -> Either a b -> b -- doesn't sound right to me
extractRight : (b -> a) -> Either a b -> a -- doesn't sound right to me

extractErr : (e -> a) -> Result e a -> a -- (corresponds to extractLeft, doesn't sound right to me)

destruct : (a -> r) -> (b -> r) -> Either a b -> r -- makes sense I think
destructLeft : (a -> b) -> Either a b -> b -- I guess it could work?
destructRight : (b -> a) -> Either a b -> a -- I guess it could work?

destructErr : (e -> a) -> Result e a -> a -- (corresponds to destructLeft)
```

I'm also not super big on naming since it takes so much time, but I'm having an idle moment :)

`elim-` might only seem natural to me because it triggers an association with elim-rules in natural deduction for me (and because I tend to think I'm trying to rid myself of the error). `destruct-` does sound pretty literal, I think I could be pretty happy with that.

Another quick thought:
```elm
caseErr : (e -> a) -> Result e a -> a
```
Not a good idea I think because obviously there can be no
```elm
case : (a -> r) -> (b -> r) -> Either a b -> r
```
just had to bring it up because it's another rather literal interpretation of what is happening.

**Comment by rehno-lindeque** [comment]
Well.... on second thought. I feel destruct might not fit that well - I mean
```elm
  let (Err e) = result
```
is destructuring assignment to me.

Feels different to case analysis
```elm
case result of 
  (Err e) -> f e
  (Success x) -> x
```

**Comment by rehno-lindeque** [comment]
@imeckler I guess maybe you'd be interested too :)

**Pull request merged**
